language: elixir
elixir:
  - 1.6.3
  - 1.7.3
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.6.3
    - otp_release: 21.0
script:
  - mix test --trace
  - MIX_ENV=prod mix do compile --warnings-as-errors, archive.build, archive.install --force
  - mix format --check-formatted
  - MIX_ENV=prod mix dialyzer --halt-exit-status
  - OUTPUT_TESTS=true mix test
  - MIX_ENV=prod mix dialyzer --list-unused-filters
  - MIX_ENV=prod mix dialyzer --unused-filters-as-errors
  - MIX_ENV=prod mix dialyzer --format short
  - MIX_ENV=prod mix dialyzer --format raw
  - MIX_ENV=prod mix dialyzer --format dialyzer
branches:
  except:
    - /^[0-9]\.[0-9]/
