language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.4
  - 1.10.4
otp_release:
  - 20.3
  - 21.3
  - 22.3
matrix:
  exclude:
    - elixir: 1.10.4
      otp_release: 20.3
  include:
    - elixir: 1.10.4
      otp_release: 23.0
script:
  - mix test --trace
  - MIX_ENV=prod mix do compile --warnings-as-errors, archive.build, archive.install --force
  - mix format --check-formatted
  - MIX_ENV=prod mix dialyzer --list-unused-filters
  - OUTPUT_TESTS=true mix test
  - MIX_ENV=prod mix dialyzer --format short
  - MIX_ENV=prod mix dialyzer --format raw
  - MIX_ENV=prod mix dialyzer --format dialyzer
  - MIX_ENV=examples mix dialyzer --format short --ignore-exit-status
branches:
  except:
    - /^[0-9]\.[0-9]/
